install.packages("mlr")
install.packages("tidyverse")
install.packages("plotly")
install.packages("mlbench")
install.packages("BBmisc")
install.packages("rpart")
install.packages("methods")
install.packages("devtools")
install.packages("RWeka")
install.packages("rpart.plot")
install.packages("partykit")
install.packages("randomForest")
install.packages("kknn")
install.packages("wordcloud")
install.packages("rattle")
install.packages("https://cran.r-project.org/src/contrib/Archive/RGtk2/RGtk2_2.20.31.tar.gz", repos=NULL)
install.packages("tm")
